### PR TITLE
Puh, mein erster neuer Blogeintrag. Ich hoffe, Du musst nicht so viel ändern. :)

### PR DESCRIPTION
**Pull request by MZ-per-X**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by sebeichholz** [comment]
I created a branch "production" (before the merge of this pull request), so I will now merge your pull request and review your changes on my machine.

**Comment by sebeichholz** [comment]
screencapture-localhost-4000-blog-de-2018-spieledatenbanken-news-012017-1519680628955
main_page

**Comment by sebeichholz** [comment]
@MZ-per-X please review the above preview of your blogpost.
I had to do only small changes (e.g. fix some line breaks and insert target="_blank" for all external links).

**Comment by sebeichholz** [comment]
@MZ-per-X or just go and checkout http://beta.oregami.org/ to preview the updated site :-)

**Comment by MZ-per-X** [comment]
Looking good - except it should be Spieldatenbanken-News 01/2017 with the date Nov 29, 2017, as in the English version.

**Comment by sebeichholz** [comment]
Ok, fixed it. It's live at http://www.oregami.org/blog/de/2017/Spieledatenbanken-News-012017

**Pull request merged**
